Add inputs components
paralect/react-starter pull request #109
Opened 2021-08-13 14:57 UTC by gloooor

2021-08-16 10:47 UTC, fihis commented on src/components/multi-select/multi-select.jsx
> +const getCustomStyle = (isError) => ({
could you move this func somewhere outside?

2021-08-16 10:48 UTC, fihis requested changes

2021-08-16 10:48 UTC, fihis commented on src/components/select/select.jsx
> +const getCustomStyle = (isError) => ({
same

2021-08-17 10:23 UTC, fihis approved these changes

2021-08-17 11:18 UTC, NesterenkoNikita approved these changes

2021-08-17 11:18 UTC, merged